### ISSUE TITLE
PUSH_PROMISE

### ISSUE THREAD

**Issue by mnot** [deweerdt/h2priograph#1]
The current process crashes when there's a PUSH_PROMISE in the trace.

I'm not really up to speed with Go, but it looks like the necessary changes are:
1. In `case OUT`, look for `HTTP2_SESSION_RECV_PUSH_PROMISE`
2. In `case IN_HEADERS`, look for `--> promised_stream_id =`

**Comment by deweerdt** [comment]
This should be fixed by #2 , thank you for reporting the issue.

**Comment by mnot** [comment]
Works, thanks!
